-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2016-03-29 20:11:44 CDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

drop table S16_PROJECT cascade constraints;                                     
drop table S16_PERSON cascade constraints;                                      
drop table S16_DEPT cascade constraints;                                        
drop table S16_CURR_PROJ cascade constraints;                                   
drop table CHI_PAR cascade constraints;

CREATE
  TABLE S16_Person
  (
    Per_id             INTEGER NOT NULL ,
    first_name         VARCHAR2 (255) ,
    last_name          VARCHAR2 (255) ,
    home_address       VARCHAR2 (255) ,
    zipcode            INTEGER ,
    home_phone         INTEGER ,
    us_citizen         VARCHAR2 (255) ,
    S16_Person_Per_id1 INTEGER ,
    is_Fired           VARCHAR2 (255) ,
    Prev_emp_sal       INTEGER ,
    employee_id        INTEGER ,
    emp_sal            INTEGER ,
    emp_sal_excption   VARCHAR2 (255) ,
    bonus              INTEGER ,
    dept_no            INTEGER ,
    is_President       VARCHAR2 (255) ,
    is_interim_manager VARCHAR2 (255) ,
    S16_dept_dept_no   INTEGER ,
    S16_Person_Per_id  INTEGER ,
    type               VARCHAR2 (255)
  ) ;
CREATE UNIQUE INDEX S16_Person__IDX ON S16_Person
  (
    S16_Person_Per_id1 ASC
  )
  ;
ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_PK PRIMARY KEY ( Per_id ) ;


CREATE
  TABLE S16_Project
  (
    Proj_id             INTEGER NOT NULL ,
    Project_title       VARCHAR2 (255) ,
    S16_dept_dept_no    INTEGER ,
    S16_Project_Proj_id INTEGER ,
    S16_Person_Per_id   INTEGER ,
    end_date_month      INTEGER ,
    end_date_day        INTEGER ,
    end_date_year       INTEGER ,
    end_person_hours    INTEGER ,
    project_active      VARCHAR2 (255) ,
    type                VARCHAR2 (255)
  ) ;
ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_PK PRIMARY KEY ( Proj_id ) ;


CREATE
  TABLE S16_curr_Proj
  (
    S16_Person_Per_id   INTEGER NOT NULL ,
    S16_Project_Proj_id INTEGER NOT NULL
  ) ;
ALTER TABLE S16_curr_Proj ADD CONSTRAINT S16_curr_Proj_PK PRIMARY KEY (
S16_Project_Proj_id, S16_Person_Per_id ) ;


CREATE
  TABLE S16_dept
  (
    dept_no   INTEGER NOT NULL ,
    dept_name VARCHAR2 (255)
  ) ;
ALTER TABLE S16_dept ADD CONSTRAINT S16_dept_PK PRIMARY KEY ( dept_no ) ;


CREATE
  TABLE chi_par
  (
    S16_Person_Per_id1 INTEGER NOT NULL ,
    S16_Person_Per_id  INTEGER NOT NULL
  ) ;
ALTER TABLE chi_par ADD CONSTRAINT chi_par_PK PRIMARY KEY ( S16_Person_Per_id1,
S16_Person_Per_id ) ;


ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_Person_FK FOREIGN KEY (
S16_Person_Per_id ) REFERENCES S16_Person ( Per_id ) ;

ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_Person_FKv1 FOREIGN KEY (
S16_Person_Per_id1 ) REFERENCES S16_Person ( Per_id ) ;

ALTER TABLE S16_Person ADD CONSTRAINT S16_Person_S16_dept_FK FOREIGN KEY (
S16_dept_dept_no ) REFERENCES S16_dept ( dept_no ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_Person_FK FOREIGN KEY (
S16_Person_Per_id ) REFERENCES S16_Person ( Per_id ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_Project_FK FOREIGN KEY (
S16_Project_Proj_id ) REFERENCES S16_Project ( Proj_id ) ;

ALTER TABLE S16_Project ADD CONSTRAINT S16_Project_S16_dept_FK FOREIGN KEY (
S16_dept_dept_no ) REFERENCES S16_dept ( dept_no ) ;

ALTER TABLE S16_curr_Proj ADD CONSTRAINT S16_curr_Proj_S16_Person_FK FOREIGN
KEY ( S16_Person_Per_id ) REFERENCES S16_Person ( Per_id ) ;

ALTER TABLE S16_curr_Proj ADD CONSTRAINT S16_curr_Proj_S16_Project_FK FOREIGN
KEY ( S16_Project_Proj_id ) REFERENCES S16_Project ( Proj_id ) ;

ALTER TABLE chi_par ADD CONSTRAINT chi_par_S16_Person_FK FOREIGN KEY (
S16_Person_Per_id ) REFERENCES S16_Person ( Per_id ) ;

ALTER TABLE chi_par ADD CONSTRAINT chi_par_S16_Person_FKv1 FOREIGN KEY (
S16_Person_Per_id1 ) REFERENCES S16_Person ( Per_id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
